config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :apps do
    resources :devices
    post "relay"
  end

  mount Sidekiq::Web, at: '/sidekiq'

  root "apps#new"

end

app/models/account.rb
class Account < ActiveRecord::Base
  extend FriendlyId
  friendly_id :uid

  has_many :devices

  before_create :generate_uid, on: :create

  protected

  def generate_uid
    self.uid = loop do
      random_uid = SecureRandom.urlsafe_base64(nil, false)
      break random_uid unless Account.exists?(uid: random_uid)
    end
  end
end

app/models/app.rb
class App < ActiveRecord::Base
  extend FriendlyId
  friendly_id :uid

  validates_uniqueness_of :key, :secret

  mount_uploader :apn_certificate, CertificateUploader

  has_many :devices
  belongs_to :user

  before_create :generate_uid, on: :create
  after_create :listen_for_events, on: :create

  protected

  def generate_uid
    self.uid = loop do
      random_uid = SecureRandom.urlsafe_base64(nil, false)
      break random_uid unless App.exists?(uid: random_uid)
    end
  end

  def listen_for_events
    Subscribe.perform_async(id, key, uid)
  end
end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :app
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :apps
end

app/controllers/accounts_controller.rb
require 'houston'
APN = Houston::Client.development

class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_filter :set_account, only: [:show, :relay]

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to account_path(@account)
    end
  end

  def relay
    @body = request.body.string
    @json = JSON.parse(@body)
    @message = @json["message"]

    @account.devices.each do |device|
      APN.certificate = File.read("/Users/adambutler/Sites/pushitrealgood/public/cert.pem")
      notification = Houston::Notification.new(device: device.token)
      notification.alert = @message
      notification.badge = @json["badge"].to_i unless @json["badge"].nil?

      notification.sound = "alert.aiff"

      APN.push(notification)
    end

    render nothing: true, status: 200
  end

  private

  def account_params
    params.require(:account).permit(:key, :secret)
  end

  def set_account
    @account = Account.friendly.find_by_uid!(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  skip_before_filter  :verify_authenticity_token
end

app/controllers/apps_controller.rb
require 'houston'
APN = Houston::Client.development

class AppsController < ApplicationController
  before_action :authenticate_user!
  before_filter :set_app, only: [:show, :relay]
  before_filter :set_apps, only: [:index]

  def new
    @app = App.new
  end

  def create
    @app = App.new(app_params)
    @app.user = current_user
    if @app.save
      redirect_to app_path(@app)
    end
  end

  private

  def app_params
    params.require(:app).permit(:key, :secret, :apn_certificate)
  end

  def set_app
    @app = current_user.apps.friendly.find_by_uid!(params[:id])
  end

  def set_apps
    @apps = current_user.apps
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

  before_filter :set_app, only: :create

  def create
    @device = Device.new(device_params)
    @device.app = @app
    if @device.save
      render json: @device
    end
  end

  private

  def device_params
    params.require(:device).permit(:token)
  end

  def set_app
    @app = App.friendly.find_by_uid!(params[:app_id])
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/show.haml
%h2
  Shweeet!
  %br
  %small
    Now lets build something awesome!

%h3 Your devices

%table
  - if @account.devices.empty?
    %tbody
      %tr
        %td You do not have any devices yet
  - else
    %thead
      %th Created at
      %th Token
    %tbody
      - @account.devices.reverse.each do |device|
        %tr
          %td= timeago_tag device.created_at
          %td
            %code= device.token

%h3
  Add this to your iOS app in the
  %code AppDelegate.m
  file just under
  %code @interface AppDelegate ()

%pre
  %code.objectivec
    :preserve
      @property NSData *deviceToken;
      @property NSMutableData *responseData;

%h3
  In the
  %code didFinishLaunchingWithOptions
  method add this -

%pre
  %code.objectivec
    :preserve
      UIUserNotificationType types = UIUserNotificationTypeAlert | UIUserNotificationTypeBadge | UIUserNotificationTypeSound;
      UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:types categories:nil];
      [application registerUserNotificationSettings:settings];

      [application registerForRemoteNotifications];

%h3 Finally add these methods to the same file

%pre
  %code.objectivec
    :preserve
      - (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
          NSLog(@"Registered with token: %@", deviceToken);
          self.deviceToken = deviceToken;
          [self postDeviceToken];
      }

      - (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
          NSLog(@"Error: %@", error);
      }

      - (void)postDeviceToken {
          NSLog(@"Hello");
          NSURL *url = [NSURL URLWithString:@"http://#{request.host}/accounts/#{@account.uid}/devices"];
          NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:url];
          request.HTTPMethod = @"POST";
          NSString *key = @"device[token]";
          NSString *value = [NSString stringWithFormat:@"%@", self.deviceToken];
          NSString *body = [NSString stringWithFormat:@"%@=%@", [key stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding], [value stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]];
          request.HTTPBody = [body dataUsingEncoding:NSUTF8StringEncoding];
          NSURLConnection *connection = [[NSURLConnection alloc] initWithRequest:request delegate:self];
          [connection start];
      }

      - (void)connection:(NSURLConnection *)connection didReceiveResponse:(NSURLResponse *)response {
          // A response has been received, this is where we initialize the instance var you created
          // so that we can append data to it in the didReceiveData method
          // Furthermore, this method is called each time there is a redirect so reinitializing it
          // also serves to clear it
          NSLog(@"Recieving reponse");
          _responseData = [[NSMutableData alloc] init];
      }

      - (void)connection:(NSURLConnection *)connection didReceiveData:(NSData *)data {
          // Append the new data to the instance variable you declared
          [_responseData appendData:data];
      }

      - (NSCachedURLResponse *)connection:(NSURLConnection *)connection
                        willCacheResponse:(NSCachedURLResponse*)cachedResponse {
          // Return nil to indicate not necessary to store a cached response for this connection
          return nil;
      }

      - (void)connectionDidFinishLoading:(NSURLConnection *)connection {
          // The request is complete and data has been received
          // You can parse the stuff in your instance variable now
          NSLog(@"Finish loading");
          NSString *string = [[NSString alloc] initWithData:self.responseData encoding:NSUTF8StringEncoding];
          NSLog(@"Response: %@", string);
      }

      - (void)connection:(NSURLConnection *)connection didFailWithError:(NSError *)error {
          // The request has failed for some reason!
          // Check the error var
          NSLog(@"Failed");
      }

%h3 Push it like this!

%pre
  %code.json
    :preserve
      {
        "channel": "apn",
        "event": "message",
        "data": { "message": "Awesome push bro!", device: "abc123" }
      }

%h3 ...or push to everybody

%pre
  %code.json
    :preserve
      {
        "channel": "apn",
        "event": "message",
        "data": { "message": "Awesome push bro!" }
      }

app/views/apps/index.haml
%h3 Your Apps

%table
  - if @apps.empty?
    %tbody
      %tr
        %td You do not have any apps yet
  - else
    %thead
      %th Key
      %th Secret
    %tbody
      - @apps.each do |app|
        %tr
          %td= link_to app.key, app_path(app.id)
          %td= link_to app.secret, app_path(app.id)

app/views/apps/new.haml
%h2 Add your app

= simple_form_for @app do |f|
  = f.input :key, label: "Pusher Key"
  = f.input :secret, label: "Pusher Secret", as: :password
  = f.input :apn_certificate, as: :file, input_html: { style: "display: block; margin: 0 auto; display: none;" }, label: "APN Certificate"
  %label.button.small{ for: "app_apn_certificate", }
    Browse
  %br
  = f.button :submit

app/views/apps/show.haml
%h2
  Shweeet!
  %br
  %small
    Now lets build something awesome!

%h3 Your devices

%table
  - if @app.devices.empty?
    %tbody
      %tr
        %td You do not have any devices yet
  - else
    %thead
      %th Created at
      %th Token
    %tbody
      - @app.devices.reverse.each do |device|
        %tr
          %td= timeago_tag device.created_at
          %td
            %code= device.token

%h3
  Add this to your iOS app in the
  %code AppDelegate.m
  file just under
  %code @interface AppDelegate ()

%pre
  %code.objectivec
    :preserve
      @property NSData *deviceToken;
      @property NSMutableData *responseData;

%h3
  In the
  %code didFinishLaunchingWithOptions
  method add this -

%pre
  %code.objectivec
    :preserve
      UIUserNotificationType types = UIUserNotificationTypeAlert | UIUserNotificationTypeBadge | UIUserNotificationTypeSound;
      UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:types categories:nil];
      [application registerUserNotificationSettings:settings];

      [application registerForRemoteNotifications];

%h3 Finally add these methods to the same file

%pre
  %code.objectivec
    :preserve
      - (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
          NSLog(@"Registered with token: %@", deviceToken);
          self.deviceToken = deviceToken;
          [self postDeviceToken];
      }

      - (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
          NSLog(@"Error: %@", error);
      }

      - (void)postDeviceToken {
          NSLog(@"Hello");
          NSURL *url = [NSURL URLWithString:@"http://#{request.host}#{app_devices_path(@app)}"];
          NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:url];
          request.HTTPMethod = @"POST";
          NSString *key = @"device[token]";
          NSString *value = [NSString stringWithFormat:@"%@", self.deviceToken];
          NSString *body = [NSString stringWithFormat:@"%@=%@", [key stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding], [value stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]];
          request.HTTPBody = [body dataUsingEncoding:NSUTF8StringEncoding];
          NSURLConnection *connection = [[NSURLConnection alloc] initWithRequest:request delegate:self];
          [connection start];
      }

      - (void)connection:(NSURLConnection *)connection didReceiveResponse:(NSURLResponse *)response {
          // A response has been received, this is where we initialize the instance var you created
          // so that we can append data to it in the didReceiveData method
          // Furthermore, this method is called each time there is a redirect so reinitializing it
          // also serves to clear it
          NSLog(@"Recieving reponse");
          _responseData = [[NSMutableData alloc] init];
      }

      - (void)connection:(NSURLConnection *)connection didReceiveData:(NSData *)data {
          // Append the new data to the instance variable you declared
          [_responseData appendData:data];
      }

      - (NSCachedURLResponse *)connection:(NSURLConnection *)connection
                        willCacheResponse:(NSCachedURLResponse*)cachedResponse {
          // Return nil to indicate not necessary to store a cached response for this connection
          return nil;
      }

      - (void)connectionDidFinishLoading:(NSURLConnection *)connection {
          // The request is complete and data has been received
          // You can parse the stuff in your instance variable now
          NSLog(@"Finish loading");
          NSString *string = [[NSString alloc] initWithData:self.responseData encoding:NSUTF8StringEncoding];
          NSLog(@"Response: %@", string);
      }

      - (void)connection:(NSURLConnection *)connection didFailWithError:(NSError *)error {
          // The request has failed for some reason!
          // Check the error var
          NSLog(@"Failed");
      }

%h3 Push it like this!

%pre
  %code.json
    :preserve
      {
        "channel": "apn",
        "event": "message",
        "data": { "message": "Awesome push bro!", device: "abc123" }
      }

%h3 ...or push to everybody

%pre
  %code.json
    :preserve
      {
        "channel": "apn",
        "event": "message",
        "data": { "message": "Awesome push bro!" }
      }

app/views/layouts/application.haml
!!!
%html
  %head
    %title Pushitrealgood
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "http://fonts.googleapis.com/css?family=Lato:100,400", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/solarized_dark.min.css", :rel => "stylesheet"}/
    %script{:src => "//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js"}
    :javascript
      hljs.initHighlightingOnLoad();
  %body
    %p.notice= notice
    %p.alert= alert

    %h1
      = link_to "Push for Pusher", root_path
    = yield
    %h4 Have fun. Built at the #{ link_to "Simpleweb", "http://simpleweb.co.uk" } #{ link_to "Pusher", "http://pusher.com" } hack night. By #{ link_to "Adam Butler", "http://lab.io" }, mobile App by #{ link_to "Jamie Maddocks", "http://chicken-studios.com" }